## Pytorch

In [1]:
import torch

In [3]:
#Crear un tensor con 5 número aleatorios.
x = torch.empty(5)
print(x)

In [10]:
#Crear un tensor que contenga dos números fijos como elemntos
x = torch.tensor([1,2])
print(x)
#Crear un tensor de dimensiones (1,2) lleno de ceros e instanciarlos
x = torch.zeros((1,2))
print(x)
#Crear un tensor lleno de unos
x = torch.ones([1,2])
print(x)

tensor([1, 2])
tensor([[0., 0.]])
tensor([[1., 1.]])


In [28]:
 #Crear tensores que estén dentro de un rango específico
 x = torch.arange(start=1, end=8)
 print(x)
 #Recuerdas para qué sirve el linspace de NumPy? Acá también puedes hacer algo parecido:
 x = torch.linspace(start=3, end=10, steps=5)
 print(x)
 #Podemos también generar un tensor con números randoms.
 x = torch.rand(5)
 print(x)
 #Halla un valor minimo y un valor máximo del tensor random q generaste, luego imprimelo.
 minimun_val = x.min()
 maximun_val = x.max()
 print(minimun_val, '-', maximun_val)

tensor([1, 2, 3, 4, 5, 6, 7])
tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])
tensor([0.2118, 0.5636, 0.6556, 0.3974, 0.4729])
tensor(0.2118) - tensor(0.6556)


In [36]:
#Definamos un tensor:

tensor_inicial = torch.tensor(
[
    [
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 0,  1,  2,  3]
    ]
    ,
    [
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [ 0,  1,  2,  3]
    ]
    ,
    [
        [17, 18, 19, 20],
        [21, 22, 23, 24],
        [ 0,  1,  2,  3]
    ]
])
print(tensor_inicial.shape)

#Linearizamos un tensor (Flatten)
flatten_tensor = tensor_inicial.flatten()
print(flatten_tensor)

torch.Size([3, 3, 4])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  0,  1,  2,  3,  9, 10, 11, 12, 13, 14,
        15, 16,  0,  1,  2,  3, 17, 18, 19, 20, 21, 22, 23, 24,  0,  1,  2,  3])


In [44]:
#Convertir un tensor de pytorch a una lista.
listed_tensor = flatten_tensor.tolist()
print(listed_tensor)
listed_inicial = tensor_inicial.tolist()
print(listed_inicial)

#Nota que cuando conviertes un tensor a lista, conserva sus dimensiones...

[1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 17, 18, 19, 20, 21, 22, 23, 24, 0, 1, 2, 3]
[[[1, 2, 3, 4], [5, 6, 7, 8], [0, 1, 2, 3]], [[9, 10, 11, 12], [13, 14, 15, 16], [0, 1, 2, 3]], [[17, 18, 19, 20], [21, 22, 23, 24], [0, 1, 2, 3]]]


#### Conceptos de Álgebra Lineal

In [72]:
#Producto punto:
A = torch.rand((5))
B = torch.rand((5))
dot_prod = A.dot(B)

print('A: {}\nB: {}'.format(A,B))
print('Dot_prod = {}'.format(dot_prod))

A: tensor([0.7248, 0.1409, 0.2473, 0.8620, 0.0554])
B: tensor([0.0049, 0.4011, 0.4323, 0.3652, 0.6769])
Dot_prod = 0.5192683339118958


In [76]:
#Matrices transpuestas:
A_t = torch.transpose(A,0,-1)
B_t = torch.transpose(B,0,-1) #Qué son los números de dim???¿?¿?¿?

print(A_t)
print(B_t)

#Probando las propiedades.
#Primera propiedad
statement = ((A_t + B_t) == torch.transpose((A+B), 0, -1))
print(statement)

#Segunda propiedad
statement = (torch.transpose(A.matmul(B), 0, -1) == B_t.matmul(A_t))
print(statement)

tensor([0.7248, 0.1409, 0.2473, 0.8620, 0.0554])
tensor([0.0049, 0.4011, 0.4323, 0.3652, 0.6769])
tensor([True, True, True, True, True])
tensor(True)


In [79]:
#Multiplicación de matrices: Con matmul.
A = torch.rand((5,3))
B = torch.rand((3,5))
print(A)
print(B)
print(A.matmul(B))

tensor([[0.1771, 0.6540, 0.9685],
        [0.8732, 0.0234, 0.7938],
        [0.0748, 0.7253, 0.8545],
        [0.6817, 0.6882, 0.4415],
        [0.5413, 0.1271, 0.9871]])
tensor([[0.6639, 0.4134, 0.3997, 0.1845, 0.6665],
        [0.1498, 0.1731, 0.6270, 0.2140, 0.1177],
        [0.6100, 0.6630, 0.9984, 0.3312, 0.6996]])
tensor([[0.8064, 0.8286, 1.4478, 0.4934, 0.8726],
        [1.0674, 0.8913, 1.1563, 0.4290, 1.1400],
        [0.6796, 0.7231, 1.3378, 0.4520, 0.7330],
        [0.8251, 0.6937, 1.1448, 0.4192, 0.8442],
        [0.9805, 0.9002, 1.2816, 0.4540, 1.0663]])


#### DETERMINANTES:

In [83]:
#Determinante
tensor = torch.rand((2,2))
print(tensor)
print("Det: {}".format(tensor.det()))
#traza
print("Traza: {}".format(torch.trace(tensor)))

tensor([[0.9018, 0.3569],
        [0.5239, 0.7900]])
Det: 0.5254444479942322
Traza: 1.6917914152145386
